name: Check website build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xf *.tar.gz
          chmod +x zola

      - name: Build Site
        run: ./zola build
